An error occurred while executing the following cell:
------------------
dot = graphviz.Digraph(format="pdf")


# superscripts = ['1', 'T']
superscripts = ["1", "J"]

train_subscript, test_subscript = "n", "m"
subscripts = [train_subscript, test_subscript]

# subgraph_labels = ['Train', 'Test']
subgraph_labels = ["Train", "Valid"]
subgraph_colors = ["/set34/4", "/paired3/2"]

edge_color = "lightsteelblue4"
fontcolor = "grey17"
hid_color, hid_fill_color = "/accent3/2", "lavender"
obs_color, obs_fill_color = "/paired3/3", "/pastel19/3"

param, hidden, observable = "Theta", "Y", "X"

dot.node("phi", "<&Phi;>", color="white", fontcolor=fontcolor)

for i, subscript in enumerate(superscripts):
    create_node(dot, param, subscript, color="white", fontcolor=fontcolor, is_greek_letter=True)
    dot.edge("phi", f"{param}{subscript}", color=edge_color)

for i, superscript in enumerate(superscripts):
    subgraph_labels = [f"Train {superscript}", f"Valid {superscript}"]
    plot_cluster(dot, subscripts, superscript, subgraph_labels, subgraph_colors)

    if i == 0:
        dot.node(f"blank{i}", "...", color="white")
        dot.edge(f"Theta{superscript}", f"blank{i}", style="invis")

file_name = "hbayes-maml"
dot.render(file_name, view=True)

dot
------------------

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/miniconda3/envs/py37/lib/python3.7/site-packages/graphviz/backend/execute.py in run_check(cmd, input_lines, encoding, quiet, **kwargs)
     80         else:
---> 81             proc = subprocess.run(cmd, **kwargs)
     82     except OSError as e:

~/miniconda3/envs/py37/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    487 
--> 488     with Popen(*popenargs, **kwargs) as process:
    489         try:

~/miniconda3/envs/py37/lib/python3.7/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:

~/miniconda3/envs/py37/lib/python3.7/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1550                             err_msg += ': ' + repr(err_filename)
-> 1551                     raise child_exception_type(errno_num, err_msg, err_filename)
   1552                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: PosixPath('dot'): PosixPath('dot')

The above exception was the direct cause of the following exception:

ExecutableNotFound                        Traceback (most recent call last)
/tmp/ipykernel_1468/2890680977.py in <module>
     34 
     35 file_name = "hbayes-maml"
---> 36 dot.render(file_name, view=True)
     37 
     38 dot

~/miniconda3/envs/py37/lib/python3.7/site-packages/graphviz/_tools.py in wrapper(*args, **kwargs)
    169                               category=category)
    170 
--> 171             return func(*args, **kwargs)
    172 
    173         return wrapper

~/miniconda3/envs/py37/lib/python3.7/site-packages/graphviz/rendering.py in render(self, filename, directory, view, cleanup, format, renderer, formatter, neato_no_op, quiet, quiet_view, outfile, engine, raise_if_result_exists, overwrite_source)
    120         args.append(filepath)
    121 
--> 122         rendered = self._render(*args, **kwargs)
    123 
    124         if cleanup:

~/miniconda3/envs/py37/lib/python3.7/site-packages/graphviz/_tools.py in wrapper(*args, **kwargs)
    169                               category=category)
    170 
--> 171             return func(*args, **kwargs)
    172 
    173         return wrapper

~/miniconda3/envs/py37/lib/python3.7/site-packages/graphviz/backend/rendering.py in render(engine, format, filepath, renderer, formatter, neato_no_op, quiet, outfile, raise_if_result_exists, overwrite_filepath)
    325                       cwd=filepath.parent if filepath.parent.parts else None,
    326                       quiet=quiet,
--> 327                       capture_output=True)
    328 
    329     return os.fspath(outfile)

~/miniconda3/envs/py37/lib/python3.7/site-packages/graphviz/backend/execute.py in run_check(cmd, input_lines, encoding, quiet, **kwargs)
     82     except OSError as e:
     83         if e.errno == errno.ENOENT:
---> 84             raise ExecutableNotFound(cmd) from e
     85         raise
     86 

ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
