An error occurred while executing the following cell:
------------------
import numpy as np

try:
    import GPy
except ModuleNotFoundError:
    %pip install gpy
    import GPy
import matplotlib.pylab as plt
import seaborn as sns
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_1869/3229858813.py in <module>
      3 try:
----> 4     import GPy
      5 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'GPy'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_1869/3229858813.py in <module>
      5 except ModuleNotFoundError:
      6     get_ipython().run_line_magic('pip', 'install gpy')
----> 7     import GPy
      8 import matplotlib.pylab as plt
      9 import seaborn as sns

ModuleNotFoundError: No module named 'GPy'
ModuleNotFoundError: No module named 'GPy'
