An error occurred while executing the following cell:
------------------
m.load_state_dict(torch.load("vae-mnist-conv-latent-dim-20.ckpt"))
m2.load_state_dict(torch.load("vae-mnist-conv-latent-dim-2.ckpt"))
------------------

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_1242/1432685684.py in <module>
----> 1 m.load_state_dict(torch.load("vae-mnist-conv-latent-dim-20.ckpt"))
      2 m2.load_state_dict(torch.load("vae-mnist-conv-latent-dim-2.ckpt"))

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    697         pickle_load_args['encoding'] = 'utf-8'
    698 
--> 699     with _open_file_like(f, 'rb') as opened_file:
    700         if _is_zipfile(opened_file):
    701             # The zipfile reader is going to advance the current file position.

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py in _open_file_like(name_or_buffer, mode)
    229 def _open_file_like(name_or_buffer, mode):
    230     if _is_path(name_or_buffer):
--> 231         return _open_file(name_or_buffer, mode)
    232     else:
    233         if 'w' in mode:

~/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py in __init__(self, name, mode)
    210 class _open_file(_opener):
    211     def __init__(self, name, mode):
--> 212         super(_open_file, self).__init__(open(name, mode))
    213 
    214     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'vae-mnist-conv-latent-dim-20.ckpt'
FileNotFoundError: [Errno 2] No such file or directory: 'vae-mnist-conv-latent-dim-20.ckpt'
